#!/usr/bin/env bash
# Tear down everything that setup_local_env.sh creates.
# Idempotent: safe to re-run.
# Usage:
#   bash scripts/cleanup_local_env.sh                 # project-local only (.venv, mlruns, trained models, dataset, caches)
#   bash scripts/cleanup_local_env.sh --stop-docker   # also stop Colima VM (keep brew packages)
#   bash scripts/cleanup_local_env.sh --stop-k8s      # also stop+delete Minikube cluster (keep brew packages)
#   bash scripts/cleanup_local_env.sh --purge-docker  # stop+delete Colima AND uninstall colima/docker/docker-compose via brew
#   bash scripts/cleanup_local_env.sh --purge-k8s     # stop+delete Minikube AND uninstall minikube/kubectl via brew
#   bash scripts/cleanup_local_env.sh --all           # everything above (project-local + stop docker + stop k8s)
#   bash scripts/cleanup_local_env.sh --purge-all     # everything above + uninstall brew packages
#
# Anything brew-installed is NEVER removed unless --purge-* is passed.
# Without flags this script only deletes files inside the project folder.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

STOP_DOCKER=0
STOP_K8S=0
PURGE_DOCKER=0
PURGE_K8S=0
ASSUME_YES=0
for a in "$@"; do
  case "$a" in
    --stop-docker)  STOP_DOCKER=1 ;;
    --stop-k8s)     STOP_K8S=1 ;;
    --purge-docker) STOP_DOCKER=1; PURGE_DOCKER=1 ;;
    --purge-k8s)    STOP_K8S=1;    PURGE_K8S=1 ;;
    --all)          STOP_DOCKER=1; STOP_K8S=1 ;;
    --purge-all)    STOP_DOCKER=1; STOP_K8S=1; PURGE_DOCKER=1; PURGE_K8S=1 ;;
    -y|--yes)       ASSUME_YES=1 ;;
    *) echo "unknown flag: $a"; exit 1 ;;
  esac
done

say()  { printf "\n\033[1;34m==> %s\033[0m\n" "$*"; }
ok()   { printf "    \033[1;32m\xe2\x9c\x93\033[0m %s\n" "$*"; }
skip() { printf "    \033[1;90m-\033[0m %s\n" "$*"; }
warn() { printf "    \033[1;33m!\033[0m %s\n" "$*"; }

confirm() {
  [ "$ASSUME_YES" = "1" ] && return 0
  printf "    \033[1;33m?\033[0m %s [y/N] " "$*"
  read -r ans
  [[ "$ans" =~ ^[Yy]$ ]]
}

rm_path() {
  local p="$1"
  if [ -e "$p" ] || [ -L "$p" ]; then
    rm -rf "$p"
    ok "removed $p"
  else
    skip "$p not present"
  fi
}

# ---------------------------------------------------------------- 1. Project-local cleanup
say "Cleaning project-local artefacts"

rm_path .venv
rm_path mlruns
rm_path .pytest_cache
rm_path htmlcov
rm_path .coverage

# Trained model artefacts (regenerated by `python src/models/train.py`)
if compgen -G "models/*.pkl" >/dev/null; then
  rm -f models/*.pkl
  ok "removed models/*.pkl"
else
  skip "no models/*.pkl present"
fi

# Downloaded dataset (regenerated by `python scripts/download_data.py`)
rm_path data/heart_disease.csv
rm_path data/heart_disease_cleaned.csv
rm_path data/dataset_info.txt

# Stray Python caches
find . -path ./.venv -prune -o -type d -name __pycache__ -print0 2>/dev/null \
  | xargs -0 -I{} rm -rf "{}" 2>/dev/null || true
find . -path ./.venv -prune -o -type f -name "*.pyc" -print0 2>/dev/null \
  | xargs -0 rm -f 2>/dev/null || true
ok "removed __pycache__ and *.pyc"

# Local API log if any
rm_path api.log

# ---------------------------------------------------------------- 2. Docker compose stack
if command -v docker >/dev/null 2>&1 && [ -f deployment/docker/docker-compose.yml ]; then
  say "Bringing down docker-compose stack (api + prometheus + grafana)"
  docker compose -f deployment/docker/docker-compose.yml down -v --remove-orphans 2>/dev/null \
    && ok "compose stack stopped" \
    || skip "compose stack was not running"
else
  skip "docker CLI not available — skipping compose teardown"
fi

# ---------------------------------------------------------------- 3. Minikube
if [ "$STOP_K8S" = "1" ]; then
  if command -v minikube >/dev/null 2>&1; then
    say "Stopping and deleting Minikube cluster"
    minikube stop    >/dev/null 2>&1 && ok "minikube stopped"  || skip "minikube was not running"
    minikube delete  >/dev/null 2>&1 && ok "minikube deleted"  || skip "minikube had no profile to delete"
  else
    skip "minikube not installed"
  fi
fi

# ---------------------------------------------------------------- 4. Colima
if [ "$STOP_DOCKER" = "1" ]; then
  if command -v colima >/dev/null 2>&1; then
    say "Stopping and deleting Colima VM"
    colima stop   >/dev/null 2>&1 && ok "colima stopped" || skip "colima was not running"
    colima delete -f >/dev/null 2>&1 && ok "colima deleted" || skip "colima had no instance to delete"
  else
    skip "colima not installed"
  fi
fi

# ---------------------------------------------------------------- 5. Brew uninstall (purge only)
# Only ever uninstall packages that brew itself installed. This keeps the
# script safe on machines where docker / kubectl come from Rancher Desktop,
# Docker Desktop, Podman or any other non-brew source.
brew_installed() {
  command -v brew >/dev/null 2>&1 && brew list "$1" >/dev/null 2>&1
}

if [ "$PURGE_K8S" = "1" ]; then
  if ! command -v brew >/dev/null 2>&1; then
    skip "brew not installed — nothing to uninstall"
  else
    say "Checking Homebrew for Minikube + kubectl"
    targets=()
    brew_installed minikube && targets+=("minikube")
    brew_installed kubectl  && targets+=("kubectl")
    if [ ${#targets[@]} -eq 0 ]; then
      skip "neither minikube nor kubectl was installed via brew"
    elif confirm "Uninstall ${targets[*]} from Homebrew?"; then
      brew uninstall --ignore-dependencies "${targets[@]}"
      ok "brew uninstall complete"
    else
      skip "user declined"
    fi
  fi
fi

if [ "$PURGE_DOCKER" = "1" ]; then
  if ! command -v brew >/dev/null 2>&1; then
    skip "brew not installed — nothing to uninstall"
  else
    say "Checking Homebrew for Colima + docker CLI + docker-compose"
    targets=()
    brew_installed colima         && targets+=("colima")
    brew_installed docker         && targets+=("docker")
    brew_installed docker-compose && targets+=("docker-compose")
    if [ ${#targets[@]} -eq 0 ]; then
      skip "no brew-managed docker stack to uninstall (your docker likely comes from Rancher/Docker Desktop/Podman)"
    elif confirm "Uninstall ${targets[*]} from Homebrew?"; then
      brew uninstall --ignore-dependencies "${targets[@]}"
      ok "brew uninstall complete"
    else
      skip "user declined"
    fi
  fi
fi

# ---------------------------------------------------------------- Summary
say "Cleanup done"
echo
echo "  Project folder is back to a clean checkout state."
echo "  To rebuild from scratch:"
echo "    bash scripts/setup_local_env.sh            # python only"
echo "    bash scripts/setup_local_env.sh --all      # python + docker + k8s"
echo
